add code to skip adding debian-security on raspberrypi boards
openmediavault/openmediavault pull request #1004
Opened 2021-04-12 17:22 UTC by ryecoaaron

Skip adding debian security on Raspbian

Raspbian and RaspberryPi OS (not 64bit) rebuild packages from debian-security.  If they do not change the version and the debian-security repo is enabled, apt will have a package checksum mismatch.

Fixes: package checksum mismatches

Signed-off-by: Aaron Murray <plugins@omv-extras.org>
"""

The Signed-off-by line is important, and it is your certification that your contributions satisfy the developers certificate or origin.

For more examples, simply use "git log" and look at some historical commits.

This was just a quick overview. More information for contributors is available here:
https://docs.openmediavault.org/en/latest/development/contribute.html
-->

- [ ] References issue
- [ ] Includes tests for new functionality or reproducer for bug

2021-04-12 18:14 UTC, votdev requested changes

2021-04-12 18:14 UTC, votdev commented on deb/openmediavault/srv/salt/omv/deploy/apt/default.sls
> +{% set rpi = salt['pillar.get']('default:OMV_IS_RPI', False) %}
Could we name this variable like this? Then it is equal to `OMV_APT_USE_KERNEL_BACKPORTS`.
```suggestion
{% set use_os_security = salt['pillar.get']('default:OMV_APT_USE_OS_SECURITY', False) %}
```

2021-04-12 18:15 UTC, votdev commented
Uahhh, i really hate such workarounds. To me it looks like RaspberryPi upstream is doing something terrible wrong.

2021-04-12 21:17 UTC, ryecoaaron commented
I understand but I don’t have a better solution.

2021-04-12 23:06 UTC, votdev requested changes

2021-04-12 23:06 UTC, votdev commented on deb/openmediavault/srv/salt/omv/deploy/apt/default.sls
> +{% set use_os_security = salt['pillar.get']('default:OMV_APT_USE_OS_SECURITY', False) %}
Could you please set this to true? On a Raspberry installation this env variable must be set explicitly.

2021-04-12 23:09 UTC, votdev requested changes

2021-04-12 23:09 UTC, votdev commented on deb/openmediavault/srv/salt/omv/deploy/apt/default.sls
> +{% if not use_os_security | to_bool %}
```suggestion
{% if use_os_security | to_bool %}
```

2021-04-12 23:09 UTC, votdev commented on deb/openmediavault/srv/salt/omv/deploy/apt/default.sls
> +{% set use_os_security = salt['pillar.get']('default:OMV_APT_USE_OS_SECURITY', False) %}
```suggestion
{% set use_os_security = salt['pillar.get']('default:OMV_APT_USE_OS_SECURITY', True) %}
```

2021-04-15 15:49 UTC, votdev approved these changes

2021-04-15 15:49 UTC, merged

2021-04-16 06:53 UTC, votdev commented
@ryecoaaron I stumbled over this code [here](https://github.com/openmediavault/openmediavault/blob/5.x/deb/openmediavault/srv/salt/omv/deploy/apt/default.sls#L105) and wonder why your PR is necessary. Salt should remove the `debian-security` repositories spread across other APT config files, so only the `/etc/apt/sources.list.d/openmediavault-debian-security.list` should exist afterwards.

2021-05-18 18:55 UTC, rabelux commented
This feature has been released, right?
Is there already an implementation of setting the env-var?

I ask because on my raspberry pi (with OMV 5.6.7) the security-repo got readded yesterday. I had removed it about a month ago.

`omv-env list` shows that the variable `OMV_APT_USE_OS_SECURITY` is known, but has no value as
`omv-env get OMV_APT_USE_OS_SECURITY` returns nothing.

I guess l can set this variable to False with `omv-env set OMV_APT_USE_OS_SECURITY False` ?

2021-05-18 19:11 UTC, ryecoaaron commented
Yes, it has been released.  The only thing that sets it is the install script.  If you have an existing install, you will need to run the omv-env command to set it.  omv-env set OMV_APT_USE_OS_SECURITY False

2021-05-18 19:31 UTC, rabelux commented
Did that, thanks for your response 👍