run shell scripts through shellcheck
openmediavault/openmediavault pull request #1522
Opened 2023-03-28 19:51 UTC by neheb

- [ ] References issue
- [ ] Includes tests for new functionality or reproducer for bug

2023-03-28 20:09 UTC, votdev requested changes
Could you please explain in detail why these changes are necessary.

2023-03-28 20:11 UTC, votdev commented
https://cbea.ms/git-commit/ may be helpful to create a PR that helps to understand why these changes are done.

2023-03-28 20:42 UTC, neheb commented on deb/openmediavault/etc/cron.daily/openmediavault-check_ssl_cert_expiry
> +  datediff_days=$(( (enddate_seconds - now_seconds) / (60 * 60 * 24) ))
$ in (()) is not needed. https://www.shellcheck.net/wiki/SC2004

2023-03-28 22:09 UTC, neheb commented
A lot of different checks are triggered:

https://www.shellcheck.net/wiki/SC2124
https://www.shellcheck.net/wiki/SC2068
https://www.shellcheck.net/wiki/SC2004
https://www.shellcheck.net/wiki/SC2046
https://www.shellcheck.net/wiki/SC2162
https://www.shellcheck.net/wiki/SC2143

2023-03-29 06:20 UTC, votdev commented
Your commitment in honor, but I have the fear that the one or the other change has side effects and things will no longer work afterwards that have worked so far without problems.

I think we now need unit tests for the changed functions.

2023-03-29 06:51 UTC, votdev commented
I still do not know your intention about this PR. Please file the PR description field why this PR is necessary.

The code has been used for years without issues now. I am critical of changing the code just for the sake of beauty.

Please split the PR into separate PRs, one for the cron jobs that can be validated easily, and one for the helper functions. It is absolutely necessary to introduce unit tests with that PR, otherwise i will not accept it.

2023-03-29 16:58 UTC, neheb commented
I was noticing issues with the check_btrfs cron scripts not finding a volume already mounted. fixed in latest version. So I decided to look at it with shellcheck. This is mostly a cleanup PR. I'll split this up.

2023-04-05 16:35 UTC, votdev commented
Thx for the tips. Superseded by https://github.com/openmediavault/openmediavault/pull/1525.

2023-04-05 16:35 UTC, closed without merging