Adding support for using partitions
openmediavault/openmediavault pull request #1539
Opened 2023-05-01 18:06 UTC by edsenabr

# Adding support for using partitions on the UI

When trying to mannualy implement something similar to that Synology calls [SHR](https://kb.synology.com/en-br/DSM/tutorial/What_is_Synology_Hybrid_RAID_SHR), one hits the wall as OMV's UI does not allow to select partitions for creating arrays or even file systems. 

This PR introduces the ability to select partitions, provided that they do not already have file systems on it. If the community finds this addition useful, I'm more than happy to make :

1. Any necessary or suggested adjustments to comply with the existing class model of the application (maybe create an Partition class inheriting from BlockDevice ?). I've given some thought on it but could not find a way to implement that would not imply in extensive refactor of the application. 
2. The extra UI's for actually running CRUD operations on  partitions

2023-05-01 18:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/openmediavault/openmediavault?pullRequest=1539) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/openmediavault/openmediavault?pullRequest=1539) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/openmediavault/openmediavault?pullRequest=1539) it.</sub>

2023-05-01 18:19 UTC, ryecoaaron commented
What is the reason partitions are needed?  You can already mount existing filesystems on partitions.  Shared folders should be fine for any separation you need to do.  If that doesn't work, use LVM to create multiple LVs.

2023-05-01 18:37 UTC, edsenabr commented
From my personal experience, I already faced 2 situations where I'd rather deal with partitions than with whole disks:

1. As Synology does on their SHR implementation, when gradually upgrading the setup with new (and larger) hard drives, one has the ability to increase the LVM by using the extra space being added by the new hard drives (as long as at least 2 were added). 
2. Let's say that I have a 5-disk setup and want a RAID-5 configuration. This setup will bring me a highly resilient file system, but with a significant performance impact. Now let's assume that I want to run an i/o intensive application with the need of a temp/volatile area that does not need resiliency: The only option I have (using the UI) is to dedicate one entire disk for this. But using the command line, I could take benefit of LVM + MDADM to create a mixed environment and leave a partition out of the LVM, in order to use it as the temp storage. 

1/ above is done by Synology's SHR. 2/ is more like an 'advanced' setup that is not even supported by Synology's UI, but is very simple to implement using OMV's UI with the changes I'm suggesting. (I already have this setup running on lab environment)

2023-05-01 18:39 UTC, edsenabr commented
TBH, I'm not entirely convinced that the way I've implemented it is the best one when following the existing coding paradigm of the project. If an alternative approach would be better, I'm happy to rewrite the code.

2023-05-01 20:37 UTC, ryecoaaron commented
> As Synology does on their SHR implementation, when gradually upgrading the setup with new (and larger) hard drives, one has the ability to increase the LVM by using the extra space being added by the new hard drives (as long as at least 2 were added).

Never used synology.  But I know LVM extremely well.  There are no reasons to use partitions with LVM and actually it works better without them in your scenario because you don't have to change partition size.   Add a disk to the VG and pvmove the old disk.  Mergerfs is also very easy to expand/upgrade drives.

> Let's say that I have a 5-disk setup and want a RAID-5 configuration. This setup will bring me a highly resilient file system, but with a significant performance impact. Now let's assume that I want to run an i/o intensive application with the need of a temp/volatile area that does not need resiliency: The only option I have (using the UI) is to dedicate one entire disk for this. But using the command line, I could take benefit of LVM + MDADM to create a mixed environment and leave a partition out of the LVM, in order to use it as the temp storage.

Why do you have use the command line for this?  Create a raid 5 array on the disks.  Create PV on the array (no partitions needed).  Create a VG from the new PV.  Create as many LVs of whatever size you need.  Create shared folders on the LVs.

I think OMV in its current config will do the things you want but not in the synology-way you are used to.

2023-05-01 21:57 UTC, edsenabr commented
> To make it short, disk partitions are not needed nowadays (for setups that OMV want to support) and I do not like them being supported in OMV because they make it more complicated than needed. 

It is really not that complicated. This PR only allows one (when creating an array or file system) to select an existing partition. 

> In OMV the OS and data devices are strictly separated by design (but there are workarounds). 

This PR does not change that

> OMV does not support partitions in the UI, but does not prevent users from using the CLI to create their special setup. 
> Mounting file systems that are located on partitions can be mounted via UI finally.

This is not true. I've created my full setup using terminal, and because the UI filters ignore partitions they are never displayed. So, If I want to to use partitions, I have to do everything by hand on the terminal, up to configuring the share (CIFS, NFS, etc), thus actually keeping me from taking benefit of the great UI you guys built. 

What this update does is only allowing one to go one step further and using partitions in addition to the basic setup

> Last but not least, the target of OMV is to support default/basic user setups and to support the user to achieve that easily. From the beginning it is NO webmin like UI where users can do everything that is possible. On the other side I try to allow users to create their special setup via CLI and support that at the last layer which is finally the file system from the OMV point of view.

I got that, but this PR does not change the concept into a webmin UI. It only allows one to choose an existing partition when creating an array or file system. A very small change (look at the size of the PR) that enables a whole new use case on the UI.

2023-05-01 22:00 UTC, edsenabr commented
> Why do you have use the command line for this? Create a raid 5 array on the disks. Create PV on the array (no partitions needed). Create a VG from the new PV. Create as many LVs of whatever size you need. Create shared folders on the LVs.

As you mentioned, when doing that I already gave the whole disks for the array, and will pay the performance penalty of parity checking for everything, even for those temporary files that do not need resiliency (think of a temp directory where a torrent client would keep its intermediate files, for instance)(

2023-05-01 22:27 UTC, ryecoaaron commented
> As you mentioned, when doing that I already gave the whole disks for the array, and will pay the performance penalty of parity checking for everything, even for those temporary files that do not need resiliency (think of a temp directory where a torrent client would keep its intermediate files, for instance)

If parity checking is the biggest bottleneck of the system, you should use hardware raid.

2023-05-01 22:31 UTC, edsenabr commented
> If parity checking is the biggest bottleneck of the system, you should use hardware raid.

Nah, that does not make any sense, as I'm able to create a perfect software based setup on OMV (that, in the end is just a layer on top of a debian box) using mdadm and lvm tools, the same way you already do on the UI. 

All this PR does is to  give the user the freedom to choose partitions in addition to disks. I don't see how why this is so controversial.

2023-05-01 22:36 UTC, edsenabr commented
This PR allows one to choose a partition on the "Create array" UI:
![image](https://user-images.githubusercontent.com/15689137/235543240-876eb94c-9f8a-44e2-882c-916eb07957ab.png)

... and on the "Create Filesystem" one:
![image](https://user-images.githubusercontent.com/15689137/235543296-975f64e4-a874-4051-ab24-5d6cbac6f7c1.png)

2023-05-01 22:39 UTC, ryecoaaron commented
> Nah, that does not make any sense, as I'm able to create a perfect software based setup on OMV (that, in the end is just a layer on top of a debian box) using mdadm and lvm tools, the same way you already do on the UI.

I basically trying to say parity won't be the bottleneck because performance with mdadm is good enough for almost every one.  If you need more performance, I was recommending using hardware raid.

using partitions with raid and having other partitions on the same disks to avoid parity will slow down the raid array due to the drive trying to write two locations at the same time on the disk.

I don't think partitions are needed at all but this isn't my decision.

2023-05-01 22:53 UTC, edsenabr commented
> I don't think partitions are needed at all but this isn't my decision.

Did you have a chance to read the SHR article I posted on the PR's description ? Lemme elaborate a little more on that; 

In addition to traditional arrays (RAID0 ~ 6 and its combinations) they allow one to create an "Hybrid" array --- called SHR  (Synology Hybrid RAID). 

This SHR is nothing more than a LVM on top of traditional arrays:
![image](https://user-images.githubusercontent.com/15689137/235544518-1ab9422f-213b-4e82-b957-c532c2384ce5.png)

when I replace 2 disks of the setup with larger ones, it expands the LV by adding another PV to it, which is basically an RAID 1 array on partitions created on the "extra space" added:
![image](https://user-images.githubusercontent.com/15689137/235544875-02df0ce6-3468-4ed4-b4fc-a1fe30bea9f3.png)

When one upgrades the third one, that array is also upgraded to RAID 5:
![image](https://user-images.githubusercontent.com/15689137/235545030-c5cd9aa2-8072-4fdd-b27c-f8fd3d682aed.png)

That way, you don't need to change all disks at once to take advantage of the extra space being added by new ones. 


**but, bear in mind that this is all transparent,  the user never has to deal with this complexity on the UI**

2023-05-01 23:13 UTC, edsenabr commented
> I basically trying to say parity won't be the bottleneck because performance with mdadm is good enough for almost every one. If you need more performance, I was recommending using hardware raid.

The thing is: When using software based arrays, all the processing has to be done by CPU. Synology has very, very poor hardware in terms of CPU, always had been this way, and the SO/HO devices does not come with raid hardware. 

So the example I gave is real: A torrent client running on a Sy box with a RAID 5 setup will bring it to its knees because of the I/O. My new setup will be in order of magnitudes faster than a Sy setup, but when going custom, I've decided to take benefits of what Sy did great (the Hybrid thing) evolving it for having a true hybrid system. 

I'm booting the Rock with an e-mmc which has a pretty decent performance for that. 

I'll mount the OMV's root partition using a RAID1 array on the SATA disks and create RAID 5 partitions for the data, leaving a RAID0 partition for the temp/volatile storage.

2023-05-01 23:25 UTC, ryecoaaron commented
This is getting off topic for your PR and would better fit the forum.  I will say I don't have time to test if this breaks any of the omv-extras storage plugins.

2023-05-01 23:40 UTC, edsenabr commented
> This is getting off topic for your PR and would better fit the forum. I will say I don't have time to test if this breaks any of the omv-extras storage plugins.

Totally agree. I'll clean up the comments to remove the off-topic chat.

2023-05-01 23:43 UTC, edsenabr commented
> I will say I don't have time to test if this breaks any of the omv-extras storage plugins.

I can test it. Additionally, I went thru the PR path because my understanding is that a plugin won't be allowed to override a core functionality like this one. Could the same thing be accomplished via plugin ?

2023-05-01 23:45 UTC, ryecoaaron commented
I don't think you need to clean it up.

2023-05-01 23:45 UTC, ryecoaaron commented
> Could the same thing be accomplished via plugin ?

I don't think so.

2023-05-02 08:18 UTC, votdev requested changes
I have an overall bad feeling with this PR and I am sure it will break code paths. There are places that assume there is no partition because the whole system is designed from beginning that this is not supported. E.g. the code path in the devices layer that lists the used and unused disks will break IMO.

2023-05-02 11:51 UTC, edsenabr commented on deb/openmediavault/usr/share/openmediavault/engined/rpc/filesystemmgmt.inc
> -		// Get a list of all detected file systems.
This code was only producing an array that was used on line 578 to check if the device has a FS on it. I 've replaced the code on line 578 to use directly the \OMV\System\Filesystem\Filesystem::hasFileSystem() function and reduce complexity. 

Do you think I should let the original one ?! This change is really not that necessary, but I thought it was worthy to simplify the code.

2023-05-02 21:14 UTC, votdev commented
This feature requires extensive testing because it breaks the workflow that was a design decision from beginning. Because of that it will not be included in the stable version 6.x.

2023-05-02 21:50 UTC, edsenabr commented
> This feature requires extensive testing because it breaks the workflow that was a design decision from beginning. Because of that it will not be included in the stable version 6.x.

No problem at all, I was not expecting it to be "simply" approved :-) Meanwhile, @votdev , can you review the other changes I've made and add you comments to it, to see if it is in good shape with your overall software design ?

2023-05-02 22:36 UTC, edsenabr commented on deb/openmediavault/usr/share/openmediavault/engined/rpc/filesystemmgmt.inc
> -		// Get a list of all detected file systems.
@votdev , this change is not required; If you feel more comfortable, I can revert the topmost but the code itself is redundant with hasFileSystem()

2024-05-06 16:39 UTC, votdev commented
I'm closing this finally because i'm not interested in that feature in OMV and I am also not aware that this is a desired function in the community.

2024-05-06 16:39 UTC, closed without merging

2024-05-06 20:25 UTC, edsenabr commented
... don´t worry, @votdev ! I've implemented it on my fork and  I'm using it from there.