Update omv-btrfs-scrub: only send mail if the scrub command found an error
openmediavault/openmediavault pull request #1709
Opened 2024-02-11 14:33 UTC by mael2

Update omv-btrfs-scrub: only send mail if the scrub command found an error
try to reduce mails from OMV.
PIPESTATUS only works in bash.
Signed-off-by: Florian Schröck [mael2@mailbox.org](mailto:mael2@mailbox.org)

This is my first pull request ever.
Let me know, if there is something to improve :)

2024-02-11 14:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/openmediavault/openmediavault?pullRequest=1709) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/openmediavault/openmediavault?pullRequest=1709) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/openmediavault/openmediavault?pullRequest=1709) it.</sub>

2024-02-11 14:47 UTC, ryecoaaron commented
In my opinion, this should be configurable not error-only.  Some users will want to receive an email on success.

2024-02-11 14:51 UTC, mael2 commented
I didn't dive into the project this deep yet, but that would be great!

2024-02-11 17:01 UTC, votdev commented
> In my opinion, this should be configurable not error-only. Some users will want to receive an email on success.

I'm also in favour of sending emails when the scan is suceeded, not only if it fails.

2024-03-22 22:50 UTC, votdev commented
Please upgrade the PR and subscribe the DCO.

2024-03-22 22:52 UTC, votdev requested changes

2024-03-22 22:52 UTC, votdev commented on deb/openmediavault/usr/sbin/omv-btrfs-scrub
> +#!/bin/bash
Please use the path returned by `which`.
```suggestion
#!/usr/bin/bash
```

2024-04-07 14:28 UTC, closed without merging

2024-04-07 14:28 UTC, mael2 commented
I don't understand how to add the signoff to a single commit where it's missing. I think I made it worse. let's forget about it.

2024-04-07 15:08 UTC, ryecoaaron commented
@mael2 just use the --signoff flag when you commit a change.  If you want to sign an existing commit, just use git commit --amend --signoff