Remove unnecessary line break in CPU usage legend
openmediavault/openmediavault pull request #806
Opened 2020-09-05 12:43 UTC by sebeksd

When using OMV_COLLECTD_RRDTOOL_GRAPH_WIDTH to make graph wider CPU legend was still split into two lines even when there was enough space for one line

Before (width 800 and 200):
![image](https://user-images.githubusercontent.com/18705953/92305265-fa76cd00-ef85-11ea-8cc3-6e156dbc7bc1.png)
![image](https://user-images.githubusercontent.com/18705953/92305229-b257aa80-ef85-11ea-9d58-5d4a4451a239.png)

After (width 800 and 200):
![image](https://user-images.githubusercontent.com/18705953/92305206-69075b00-ef85-11ea-8b56-51ee1c2d3bc2.png)
![image](https://user-images.githubusercontent.com/18705953/92305214-8e946480-ef85-11ea-9a85-c37a608362c0.png)

2020-09-05 12:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/openmediavault/openmediavault?pullRequest=806) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/openmediavault/openmediavault?pullRequest=806) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/openmediavault/openmediavault?pullRequest=806) it.</sub>

2020-09-05 13:18 UTC, votdev commented
Please adapt your PR according to https://openmediavault.readthedocs.io/en/5.x/development/contribute.html#contribution-rules.

2020-09-05 19:20 UTC, votdev commented
I'm sorry, the `Signed-off-by` must be added to the commit message, otherwise this information can get lost.

2020-09-05 19:23 UTC, sebeksd commented
Signed-off-by in both commit and pull request

2020-09-05 20:25 UTC, votdev commented
Seems it does not work. The first and last legend entries are cut off.
![Bildschirmfoto vom 2020-09-05 22-23-53](https://user-images.githubusercontent.com/1897962/92312978-84df2100-efc6-11ea-9db9-183504c04a46.png)

2020-09-05 20:26 UTC, votdev requested changes
Seems it does not work with default values. The first and last legend entries are cut off.
![Bildschirmfoto vom 2020-09-05 22-23-53](https://user-images.githubusercontent.com/1897962/92312978-84df2100-efc6-11ea-9db9-183504c04a46.png)

2020-09-05 21:33 UTC, sebeksd commented
Fixed. (Amended last commit)

It's my first time changing something in rrdtool graphs, but it seems that old graph had same issue as you pointed (but of course not on default settings).
Now after a little change it seems to play well with every width (not cutting anything), only thing that I don't like in my change is regarding default width of 400 because with that settings single "label" is in new line, but maybe this is fine ?
Changing default to 450 will make it a single line (but not sure if you like that).

Some screens:
at 400 (default)
![image](https://user-images.githubusercontent.com/18705953/92313784-d8a23800-efcf-11ea-9474-5c8287c4a87f.png)

at 450
![image](https://user-images.githubusercontent.com/18705953/92313793-e952ae00-efcf-11ea-912d-ca416e921366.png)

at 300
![image](https://user-images.githubusercontent.com/18705953/92313798-f8396080-efcf-11ea-939e-cad19a7f76ac.png)

at 800
![image](https://user-images.githubusercontent.com/18705953/92313804-0dae8a80-efd0-11ea-805e-b615ded24efc.png)

2020-09-08 06:13 UTC, votdev requested changes
Thanks, looks OK now. Could you please squash your PR into one commit? The commit `Merge branch 'master' into master` isn't really necessary.

2020-09-08 06:29 UTC, sebeksd commented
Merge commit deleted, all changes are in single commit, is it ok now ?

2020-09-08 06:41 UTC, merged